### ISSUE TITLE
Cursor positioned 1 character to the right when comment starts at beginning of line

### ISSUE THREAD

**Issue by ralesk** [SublimeText/GoToEndOfLineOrScope#2]
Pressing End looks like this:
`// blah blah| blah`
`// blah blah blah|`
`/|/ blah blah blah` ← ?!
`// blah blah blah|`

If there's anything before the comment, the cursor is correctly positioned to the beginning of the comment.

**Comment by keith-hall** [comment]
thanks for reporting. This should now be fixed by https://github.com/SublimeText/GoToEndOfLineOrScope/commit/f1e442d75594e49f4c57461382162818ceb72d1f (though it may take a while for Package Control to see the updated version). Please let me know how it goes :)

**Comment by ralesk** [comment]
Seems to work, thanks!
